### ISSUE TITLE
Separate territory images

### ISSUE THREAD

**Issue by CheAle14** [TheGrandCoding/board-game#1]
As per the [`Dangers/Assets/Images/Territories/NA_Alaska.png`](https://github.com/TheGrandCoding/board-game/blob/master/Danger/Assets/Images/Territories/NA_Alaska.png) file, extract each territory and give a similar naming file. Additionally, provide each continent a unique colour (eg, N. America can be yellow) and give each territory in that continent a different shade of that colour.

Territories to do:

- [x] **North America** (yellow)
    - [x] Alaska
    - [x] Alberta
    - [x] Central America
    - [x] Eastern US
    - [x] Greenland
    - [x] Northwest Territory
    - [x] Ontario
    - [x] Quebec
    - [x] Western US

- [x] **South America**
    - [x] Argentina
    - [x] Brazil
    - [x] Peru
    - [x] Benezuela
- [x] **Europe**
    - [x] Great Britain
    - [x] Iceland
    - [x] Northern Europe
    - [x] Scandinavia
    - [x] Southern Europe
    - [x] Ukraine
    - [x] Western Europe
- [x] **Africa**
    - [x] Congo
    - [x] East Africa
    - [x] Egypt
    - [x] Madagascar
    - [x] North Africa
    - [x] South Africa
- [x] **Asia**
    - [x] Afganistan
    - [x] China
    - [x] India
    - [x] Irkutsk
    - [x] Japan
    - [x] Kamchatka
    - [x] Middle East
    - [x] Mongolia
    - [x] Siam
    - [x] Siberia
    - [x] Ural
    - [x] Yakutsk
- [x] **Australia**
    - [x] Eastern Aus
    - [x] Indonesia
    - [x] New Guinea
    - [x] Western Aus

**Comment by CheAle14** [comment]
So.. none of these images are using the same ratios/resolution as the main map thingy
The way I did it was to use gimp/photoshop/paint.net or whatever to 'lasso' around the territory on the map, then crop to that selection, so that it was the same ratio/size.
But I'm unable to easily transfer the images you've done to the actual map - especially since none of them seem to have their own scale?
unless i'm being stupid and trying to do it wrong

**Comment by CheAle14** [comment]
![image](https://user-images.githubusercontent.com/12370876/50574599-7dc04280-0de3-11e9-85ec-8cb333ad567f.png)
Example of what i mean - they dont seem to match properly, and I've used varying "Scales" to make it seem like the above

**Comment by BOOseungkwan** [comment]
renamed 'north africa' to 'west africa' because it is in the west
