### ISSUE TITLE
Some sort of basic UI

### ISSUE THREAD

**Issue by CheAle14** [TheGrandCoding/board-game#12]
It should be able to display information related to:
* you (name etc) 
* the currently selected territory (name, continent, armies on it etc) 
* and whoever owns the current territory (their name etc)

**Comment by CheAle14** [comment]
I'm going to assign this to @BOOseungkwan in the hopes that you'll actually do something nice with the UI

**Comment by anushan001** [comment]
Makes everything bigger

**Comment by CheAle14** [comment]
what do you mean by bigger
![image](https://user-images.githubusercontent.com/12370876/50987786-819a4600-1502-11e9-82e6-3f5d86790077.png)
its already huuge

**Comment by anushan001** [comment]
wow

**Comment by CheAle14** [comment]
@BOOseungkwan has anything been done on this?
