### ISSUE TITLE
Only trigger OnClick when it is not a background

### ISSUE THREAD

**Issue by CheAle14** [TheGrandCoding/board-game#4]
In the `ImageButton` class, check the alpha of the clicked pixel to ensure that it is not currently a background pixel
For example: Clicking in the sea to the West of Alaska will currently trigger the onclick, but it shouldnt - because you're clicking the sea

**Comment by anushan001** [comment]
How do u assign something to urself
cuz i dont think that i can do it

**Comment by CheAle14** [comment]
![image](https://user-images.githubusercontent.com/12370876/50572698-70905d00-0dbd-11e9-8ba4-0d10ae9426a6.png)
I may need to add you to the repo, let me check

**Comment by CheAle14** [comment]
Added the TheGrandCoding/Games team, which you are a member of, so reload and try again?

**Comment by anushan001** [comment]
yh it worked

**Comment by anushan001** [comment]
just checking the alpha won't work as if u click on very eastern Canada it will still trigger Alaska

**Comment by CheAle14** [comment]
True since the images are rectangles but the 'hitbox' shouldnt be.
There must be a way of allowing the event to continue and trigger on another image in the same place?

**Comment by anushan001** [comment]
How about if u have words on each territory saying the name of the territory which triggers the action
instead of the images

**Comment by CheAle14** [comment]
You could have buttons/text on a more internal location true
But what about smaller places like the UK? It'd be hard to see & click that
If there's no other way or its difficult to make it so the images trigger then we can do it that way

**Comment by anushan001** [comment]
if it is too small we could hav it outside the territory

**Comment by anushan001** [comment]
@CheAle14 why would I need to check the alpha, as the white is fully opaque

**Comment by anushan001** [comment]
@CheAle14 I give up
I cannot do it

**Comment by CheAle14** [comment]
![image](https://user-images.githubusercontent.com/12370876/50601282-a1e75680-0eab-11e9-8607-9f23fd8b7745.png)
I'll give it a go, gonna use the maths above

**Comment by CheAle14** [comment]
![image](https://user-images.githubusercontent.com/12370876/50681635-26e58380-1004-11e9-92c9-7feac4a550b8.png)
I am not sure if this is possible given that the x/y axis are going in different directions (well, the y-axis is: its going up from centre, but down from topleft... which mean we have to flip the sign mm)
![image](https://user-images.githubusercontent.com/12370876/50681840-cc005c00-1004-11e9-9a01-c2fef6442f43.png)
Upon further though I think those are the formulas, will throw into unity

**Comment by anushan001** [comment]
@CheAle14 how's it going?

**Comment by CheAle14** [comment]
Just to describe where this is at the moment:

* @SneakyBoy10 is going to attempt to use Raycasts
* @BOOseungkwan was talking about attempting to change the shape of the sprites to actually be the shape of the land(mass) rather than a rectangle.
* @CheAle14 is going to do nothing, because he's given up. good luck you two

**Comment by SneakyBoy10** [comment]
nice

**Comment by CheAle14** [comment]
Raycast idea fell through - not possible to find exact pixel, only object it passes through

If @BOOseungkwan is unable to figure this out then the issue should be closed and we wont do it / we'll come back to it later

**Comment by BOOseungkwan** [comment]
better luck tomorrow?
story so far: can use sprite editor to change the shape of the sprite, but unity then ignores the whole image altogether ?? Tried messing about with sprite renderers and mask and all that but /shrug
