### ISSUE TITLE
Start game functionality (initial owning of territories)

### ISSUE THREAD

**Issue by CheAle14** [TheGrandCoding/board-game#9]
At the game start:
1) Players will each have a dice roll
2) Whoever has the highest roll goes first, then next highest, etc, in order to do one each of the following per person:
3) Select their capital
4) The remaining territories will be split evenly (and randomly) between the players.

**Comment by SneakyBoy10** [comment]
@CheAle14 r u implying they do the distribution themselves cause I assumed we would do it randomly

**Comment by CheAle14** [comment]
Well I think I read somewhere that players would chose until no territories remained, but maybe not
Though I can think of a few ways that we can do this:
1) Players chose capital *and* all territories (so no randomness at all)
2) Players chose capitals, but remaining territories is split randomly
3) Capitals are randomly picked, but they get to picked territories
4) Completely random - capitals and territories all random
5) No capitals at all, and its all random

@SneakyBoy10

**Comment by SneakyBoy10** [comment]
what i thought we could do was to randomly distribute territories between players and then there first turn is them picking a capital from one of there assigned territories

**Comment by CheAle14** [comment]
I have added in most of the logic/code for it, just need to add a UI setup for each player to select their capital (at the moment, it'll do it randomly)

**Comment by CheAle14** [comment]
I'm thinking of adding a helper function, perhaps called `NextTerritoryClickedAsync()` that:
* displays a UI pop-up with a given message, and 
* listens to every territory's "Clicked" event - or perhaps each territory calls a function in the UI class
* then, displays the clicked territory in the UI, now with a confirm button..
* if confirm clicked, then it finally returns the program flow back to wherever the function was called and returns that territory
* if not, the player can continue to click around until it is selected
* *possibly: add 'criteria' so you can specify only from one continent, or a territory that is owned by one player, or not owned by one player, or that has x number of armies in, etc.*

This should also add some future proofing as it would be a nice function to have (ie, when it comes to attacking/moving troops etc)
